### ISSUE TITLE
MovementAlert does not work with JOSM 14253+

### ISSUE THREAD

**Issue by don-vip** [maripo/JOSM_movementalert#5]
`Main` was deprecated. It's gone in [JOSM 14253](https://josm.openstreetmap.de/changeset/14253/josm/).

`Main.parent` must be replaced by `MainApplication.getMainFrame()` (introduced in [JOSM 14140](https://josm.openstreetmap.de/changeset/14140/josm)).

`Main.pref` must be almost always replaced by `Config.getPref()` (introduced in [JOSM 12847](https://josm.openstreetmap.de/changeset/12847/josm)).
Few advanced methods can only be called from `Preferences.main()` (introduced in [JOSM 14149](https://josm.openstreetmap.de/changeset/14149/josm)).

Plugin must be [updated](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/jdk=JDK8/2081/warnings3Result/type.-1217143347/) and a new version released.

**Comment by floscher** [comment]
@maripo How does [release `v1.3`](https://github.com/maripo/JOSM_movementalert/releases/tag/v1.3) solve this issue, when it [still contains `Main.parent`](https://github.com/maripo/JOSM_movementalert/blob/a08480cbbab1eb786551adad511d4a1b235cd7cc/src/org/maripo/josm/movementalert/MovementAlertPlugin.java#L63)?

Could it be that the *.jar is built from different source code, that is not yet pushed to GitHub?

**Comment by maripo** [comment]
Sorry, I forgot to push & commit.
https://github.com/maripo/JOSM_movementalert/commit/a61fc35ec04bec11bb20a50e8f417a23d8c5bd89
